version: "3"

services:
    frontend:
        image: kuuku123/ipl-dashboard:frontend
        ports:
            - "3000:3000"
        depends_on: 
            - backend


    backend:
        container_name: backend
        restart: on-failure
        image: kuuku123/ipl-dashboard:backend
        ports:
            - "8080:8080"
        environment:
            MYSQL_HOST: mysql-server
            MYSQL_PORT: 3306
        depends_on:
            - mysql-server

    db:
        image: kuuku123/ipl-dashboard:mysql
        container_name: mysql-server
        #environment:
        #- MYSQL_DATABASE=ipl_dashboard
        #- MYSQL_ROOT_PASSWORD=1234
        #- TZ=Asia/Seoul


